export {default as aircraftRouter} from './aircraft.routes'
export {default as classRouter} from './class.routes'
export {default as instructorRouter}from './instructor.routes'
export {default as pilotRouter} from './pilot.routes'
export {default as studentRouter} from './student.routes'
export {default as sessionsRouter} from './sessions.routes'