version: '3'
services: 
  database:
    image: 'postgres:latest'
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - "9000:5432"

volumes: 
  db-data:

